version: '3.1'

services:

  db:
    image: mariadb
    container_name: tashark_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 53Dou-_kSflL
      MYSQL_DATABASE: tashark
      MYSQL_USER: tashark_user
      MYSQL_PASSWORD: XK_3-rRxeUZ5
    volumes:
      - ../db:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:9001